In [1]:
import pandas as pd

# pandas 数据结构 Series
ser_obj = pd.Series(range(10, 20), index=list('abcdefhjkl'))
# 头部
print(ser_obj.head(9))
print(type(ser_obj.index))
print(ser_obj.index)
print(type(ser_obj.values))
print(ser_obj.values)
print(ser_obj[8])

# dict 构建series
year_dict = {2001: 123, 1382: 23.2, 2077: 21.1}
ser_obj1 = pd.Series(year_dict)
print(ser_obj1)

# 为index、series取别名
ser_obj1.name = '年份表'
ser_obj1.index.name = 'year'
print(ser_obj1)

a    10
b    11
c    12
d    13
e    14
f    15
h    16
j    17
k    18
dtype: int64
<class 'pandas.core.indexes.base.Index'>
Index(['a', 'b', 'c', 'd', 'e', 'f', 'h', 'j', 'k', 'l'], dtype='object')
<class 'numpy.ndarray'>
[10 11 12 13 14 15 16 17 18 19]
18
2001    123.0
1382     23.2
2077     21.1
dtype: float64
year
2001    123.0
1382     23.2
2077     21.1
Name: 年份表, dtype: float64


In [49]:
import numpy as np
import pandas as pd

# DataFrame的构建
a = pd.DataFrame(np.arange(12).reshape(3, 4))
print(a)
b = np.random.randn(3, 4)
print(b)
print('-' * 20)
# dict 构建
dict_data = {'A': 1,
             'B': pd.date_range('20190926', periods=4),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([3] * 4, dtype='int32'),
             'E': ['python', 'java', 'c++', 'c'],
             'F': 'wangdao'}
c = pd.DataFrame(dict_data)
print(c)
# 列索引操作
print(c['A'])
c['h'] = c['C'] * 4
del (c['D'])
print(c)
# 索引名切片
print(c.loc['0':'2', ['B', 'F']])
print('-' * 20)
# 基于索引编号进行切片
print(c.iloc[0:3, [1, 4]])
c.dtypes

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
[[ 0.15966276 -1.51436794  0.74079167  0.03841277]
 [-1.63728101  1.37417529  0.79962169  2.28971619]
 [-0.57224341  0.58040952  0.63424842 -0.69408966]]
--------------------
   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  python  wangdao
1  1 2019-09-27  1.0  3    java  wangdao
2  1 2019-09-28  1.0  3     c++  wangdao
3  1 2019-09-29  1.0  3       c  wangdao
0    1
1    1
2    1
3    1
Name: A, dtype: int64
   A          B    C       E        F    h
0  1 2019-09-26  1.0  python  wangdao  4.0
1  1 2019-09-27  1.0    java  wangdao  4.0
2  1 2019-09-28  1.0     c++  wangdao  4.0
3  1 2019-09-29  1.0       c  wangdao  4.0
           B        F
0 2019-09-26  wangdao
1 2019-09-27  wangdao
2 2019-09-28  wangdao
--------------------
           B        F
0 2019-09-26  wangdao
1 2019-09-27  wangdao
2 2019-09-28  wangdao


A             int64
B    datetime64[ns]
C           float32
E            object
F            object
h           float32
dtype: object

In [1]:

import numpy as np
import pandas as pd

# 对齐操作
s1 = pd.Series(range(10, 20), index=range(10))
s2 = pd.Series(range(5, 10), index=range(5))
print(s1 + s2)

d1 = pd.DataFrame(np.ones((2, 2)), columns=['a', 'b'])
d2 = pd.DataFrame(np.ones((3, 3)), columns=['a', 'b', 'c'])
print(d1 + d2)
d3 = pd.DataFrame(np.random.randn(4, 6) - 1)
# 填充数据 add  sub div mul 可选字段fill_value填充
print(s1.add(s2, fill_value=0))
print(d1.sub(d2, fill_value=-2.))
print('-' * 20)
print(np.abs(d3))
# 作用到指定轴方向数据
print(d3.apply(lambda x: x.max(), axis=1))
# 作用到每个数据
print(d3.applymap(lambda x: '%.2f' % x))

0    15.0
1    17.0
2    19.0
3    21.0
4    23.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64
     a    b   c
0  2.0  2.0 NaN
1  2.0  2.0 NaN
2  NaN  NaN NaN
0    15.0
1    17.0
2    19.0
3    21.0
4    23.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64
     a    b    c
0  0.0  0.0 -3.0
1  0.0  0.0 -3.0
2 -3.0 -3.0 -3.0
--------------------
          0         1         2         3         4         5
0  0.932974  0.109161  1.865406  1.457567  0.812741  0.545392
1  0.317812  1.278414  1.776520  0.155828  4.111979  2.665433
2  0.993221  1.112622  1.181274  1.936307  0.232907  0.221762
3  1.556675  0.407524  0.731760  1.429567  0.895002  3.713514
0   -0.109161
1    0.317812
2    0.232907
3    0.895002
dtype: float64
       0      1      2      3      4      5
0  -0.93  -0.11  -1.87  -1.46  -0.81  -0.55
1   0.32  -1.28  -1.78  -0.16  -4.11  -2.67
2  -0.99  -1.11  -1.18  -1.94   0.23  -0.22
3  -1.56  -0.41  -0.73  -1.43   0.90  -3.71


In [18]:
s1 = pd.Series(range(10, 25), index=np.random.randint(200, size=15))
# series 索引排序
print(s1.sort_index())

d3 = pd.DataFrame(np.random.randn(4, 6) - 1,
                  index=['a', 'b', 'e', 'c'],
                  columns=['4', '6', '2', '1', '9', '0'])
print(d3)
# ascending 降序/升序排序
print(d3.sort_index(axis=1, ascending=False))
# 值排序，只能指定列名columns
print(d3.sort_values(by='0'))

d4 = d1 + d2
print(d4)
# 控制判断
print(d4.isnull())
# 缺失数据，丢弃对应行列
print(d4.dropna())
# 填充缺失数据
print(d4.fillna(5.4))

2      21
8      13
17     10
28     17
29     20
30     15
94     16
120    14
140    19
145    18
153    12
162    11
162    24
165    22
168    23
dtype: int64
          4         6         2         1         9         0
a  0.110397 -1.497829 -0.466893 -1.883658 -0.446508 -2.136137
b -1.518125 -1.164549 -1.012391 -1.605042 -0.855233 -3.860698
e -0.258898 -0.943417 -2.335238  0.536673 -1.470872 -1.437847
c -1.872298 -1.102281 -2.950146 -1.647242 -0.975542 -1.835190
          9         6         4         2         1         0
a -0.446508 -1.497829  0.110397 -0.466893 -1.883658 -2.136137
b -0.855233 -1.164549 -1.518125 -1.012391 -1.605042 -3.860698
e -1.470872 -0.943417 -0.258898 -2.335238  0.536673 -1.437847
c -0.975542 -1.102281 -1.872298 -2.950146 -1.647242 -1.835190
          4         6         2         1         9         0
b -1.518125 -1.164549 -1.012391 -1.605042 -0.855233 -3.860698
a  0.110397 -1.497829 -0.466893 -1.883658 -0.446508 -2.136137
c -1.872298 -1.102281 -2.950146

In [21]:
import pandas as pd
import numpy as np

s1 = pd.Series(np.random.randn(12), index=[['a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c', 'c'],
                                           [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]])
# 层级索引
# print(s1.index)
# print(type(s1.index))
print(s1)
# 获取数据
# 外层数据获取
print(s1['a'])
# 内层选取
print(s1[:, 4])
#
print(s1['c',8])
# 内外层索引交换
    # print(s1.swaplevel())
# 索引“降维”，二级索引->dataframe类型 参数为层级所以层数，可以指定层级为columns
print(s1.unstack(0))

a  0     1.023341
   1     2.668062
   2     0.187836
   3     1.836211
b  4     1.497297
   5    -0.428820
   6     0.395028
   7    -0.202745
c  8     1.384748
   9    -0.972670
   10   -1.095484
   11   -0.206702
dtype: float64
0    1.023341
1    2.668062
2    0.187836
3    1.836211
dtype: float64
b    1.497297
dtype: float64
1.38474827064492
           a         b         c
0   1.023341       NaN       NaN
1   2.668062       NaN       NaN
2   0.187836       NaN       NaN
3   1.836211       NaN       NaN
4        NaN  1.497297       NaN
5        NaN -0.428820       NaN
6        NaN  0.395028       NaN
7        NaN -0.202745       NaN
8        NaN       NaN  1.384748
9        NaN       NaN -0.972670
10       NaN       NaN -1.095484
11       NaN       NaN -0.206702
0   a    1.023341
1   a    2.668062
2   a    0.187836
3   a    1.836211
4   b    1.497297
5   b   -0.428820
6   b    0.395028
7   b   -0.202745
8   c    1.384748
9   c   -0.972670
10  c   -1.095484
11  c   -0.206702
dtype: 

In [1]:
import pandas as pd
import numpy as np
s1 = pd.DataFrame(np.random.randn(3,5),index=range(3),columns=range(5))
print(s1)
print('-'*20)
# Pandas内置计算函数,skipna跳过缺失值  内置sum mean max min std ...
print(s1.max(axis=0,skipna=False))
# 数据统一进行多个计算（默认的）
print(s1.describe())

          0         1         2         3         4
0 -0.029929  0.260997 -0.108921  0.510665  0.366114
1  1.765634  0.037075  1.319921 -1.407913  0.183348
2 -0.524506 -1.515550  0.918815 -0.954792 -1.049429
--------------------
0    1.765634
1    0.260997
2    1.319921
3    0.510665
4    0.366114
dtype: float64
              0         1         2         3         4
count  3.000000  3.000000  3.000000  3.000000  3.000000
mean   0.403733 -0.405826  0.709938 -0.617347 -0.166656
std    1.205086  0.967549  0.736967  1.002815  0.769947
min   -0.524506 -1.515550 -0.108921 -1.407913 -1.049429
25%   -0.277218 -0.739237  0.404947 -1.181353 -0.433041
50%   -0.029929  0.037075  0.918815 -0.954792  0.183348
75%    0.867852  0.149036  1.119368 -0.222064  0.274731
max    1.765634  0.260997  1.319921  0.510665  0.366114


In [2]:
# pandas 分组、聚合
import pandas as pd
import numpy as np
dict_obj = {'key1' : ['a', 'b', 'a', 'b',
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randn(8),
            'data2': np.random.randn(8)}
s1 = pd.DataFrame(dict_obj)
print(s1)
# 只能由columns进行分组
print(s1['data1'].groupby(s1['key1']).mean())
# size显示分组及组成员个数
print(s1['data1'].groupby(s1['key1']).size())
print(s1.groupby([s1['key1'],s1['key2']]).size())
print(s1.groupby(['key2','key1']).mean())

  key1   key2     data1     data2
0    a    one -1.117657 -0.226540
1    b    one  0.564864 -0.808608
2    a    two -0.721997  0.113026
3    b  three  0.182954 -0.652602
4    a    two -0.995119  0.880456
5    b    two -0.771945 -0.616144
6    a    one  0.730544  0.286989
7    a  three -0.702447  1.450673
key1
a   -0.561335
b   -0.008042
Name: data1, dtype: float64
key1
a    5
b    3
Name: data1, dtype: int64
key1  key2 
a     one      2
      three    1
      two      2
b     one      1
      three    1
      two      1
dtype: int64
               data1     data2
key2  key1                    
one   a    -0.193557  0.030224
      b     0.564864 -0.808608
three a    -0.702447  1.450673
      b     0.182954 -0.652602
two   a    -0.858558  0.496741
      b    -0.771945 -0.616144


In [3]:
# pandas 时间序列
print(pd.date_range('20190123', periods=6))

DatetimeIndex(['2019-01-23', '2019-01-24', '2019-01-25', '2019-01-26',
               '2019-01-27', '2019-01-28'],
              dtype='datetime64[ns]', freq='D')


In [1]:
# 重采样


In [11]:
import numpy as np
import pandas as pd
# 分组运算
dict_obj = {'key1' : ['a', 'b', 'a', 'b',
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randint(1, 10, 8),
            'data2': np.random.randint(1, 10, 8)}
df_obj = pd.DataFrame(dict_obj)
print(df_obj)
# add_prefix在columns名前加标签，add_suffix后面
sum1 = df_obj.groupby('key1').sum().add_prefix('前面标签 ')
print(df_obj.groupby('key1').sum().add_prefix('前面标签 '))

  key1   key2  data1  data2
0    a    one      6      3
1    b    one      4      9
2    a    two      7      9
3    b  three      2      7
4    a    two      7      8
5    b    two      9      3
6    a    one      8      2
7    a  three      8      7
              前面标签 key2  前面标签 data1  前面标签 data2
key1                                           
a     onetwotwoonethree          36          29
b           onethreetwo          15          19


In [13]:
# 表的合并，参数限定了只能左右拼接
# on 拼接的主键，如果俩表列名不一样但是内容一样可以使用left/right_on
k1_sum = pd.merge(df_obj,sum1,left_on='key1',right_index=True)
k1_sum

key1   key2  data1  data2          前面标签 key2  前面标签 data1  前面标签 data2
0    a    one      6      3  onetwotwoonethree          36          29
2    a    two      7      9  onetwotwoonethree          36          29
4    a    two      7      8  onetwotwoonethree          36          29
6    a    one      8      2  onetwotwoonethree          36          29
7    a  three      8      7  onetwotwoonethree          36          29
1    b    one      4      9        onethreetwo          15          19
3    b  three      2      7        onethreetwo          15          19
5    b    two      9      3        onethreetwo          15          19

In [17]:
import numpy as np
import pandas as pd
# 合并，合并后数据形状不变，transform速度快，代码短
dict_obj = {'key1' : ['a', 'b', 'a', 'b',
                      'a', 'b', 'a', 'a'],
            'key2' : ['one', 'one', 'two', 'three',
                      'two', 'two', 'one', 'three'],
            'data1': np.random.randint(1, 10, 8),
            'data2': np.random.randint(1, 10, 8)}
df_obj = pd.DataFrame(dict_obj)
print(df_obj)
sum_tf = df_obj.groupby('key1').transform(np.sum).add_prefix('sum_')
df_obj[sum_tf.columns] = sum_tf
df_obj

  key1   key2  data1  data2
0    a    one      8      9
1    b    one      5      9
2    a    two      6      8
3    b  three      2      6
4    a    two      3      5
5    b    two      2      1
6    a    one      6      1
7    a  three      4      8
            sum_key2  sum_data1  sum_data2
0  onetwotwoonethree         27         31
1        onethreetwo          9         16
2  onetwotwoonethree         27         31
3        onethreetwo          9         16
4  onetwotwoonethree         27         31
5        onethreetwo          9         16
6  onetwotwoonethree         27         31
7  onetwotwoonethree         27         31
Index(['sum_key2', 'sum_data1', 'sum_data2'], dtype='object')


key1   key2  data1  data2           sum_key2  sum_data1  sum_data2
0    a    one      8      9  onetwotwoonethree         27         31
1    b    one      5      9        onethreetwo          9         16
2    a    two      6      8  onetwotwoonethree         27         31
3    b  three      2      6        onethreetwo          9         16
4    a    two      3      5  onetwotwoonethree         27         31
5    b    two      2      1        onethreetwo          9         16
6    a    one      6      1  onetwotwoonethree         27         31
7    a  three      4      8  onetwotwoonethree         27         31

In [2]:
!dir

 驱动器 E 中的卷是 新加卷
 卷的序列号是 A823-8A6A

 E:\Code\DataAnaly\Pandas 的目录

2023/06/22  19:44    <DIR>          .
2023/06/22  13:02    <DIR>          ..
2023/06/18  10:24    <DIR>          .ipynb_checkpoints
2023/06/22  19:44            28,734 StructTest.ipynb
               1 个文件         28,734 字节
               3 个目录 498,683,969,536 可用字节


## 数据合并

In [25]:
import  numpy as np
import pandas as pd
# np的合并
arr1 = np.random.randint(0,10,(3,4))
arr2 = np.random.randint(9,20,(3,4))
print(np.concatenate([arr1,arr2],axis=1))
# pandas  series合并
ser1 = pd.Series(np.random.randint(0,10,5),index=range(0,5))
ser2 = pd.Series(np.random.randint(0,10,4),index=range(5,9))
print(pd.concat([ser1, ser2]))
# df合并
df1 = pd.DataFrame(np.random.randint(0,19,(3,5)),index=range(3),columns=range(5))
df2 = pd.DataFrame(np.random.randint(0,19,(3,4)),index=range(3),columns=range(4))
# 合并不存在的列，会自动填充nan;
# 也可以选择连接方式，内连接inner只会合并两者的形状交集
print(pd.concat([df1, df2],axis=0,join='inner'))
print('-'*20)
print(df1)
# 数据重构，降升维
print(df1.stack().unstack(0))

[[ 6  7  1  2 17 19 13 15]
 [ 4  1  4  1 17 13 19 15]
 [ 7  7  3  5 19 11 14 12]]
0    0
1    4
2    0
3    3
4    4
5    6
6    3
7    1
8    7
dtype: int32
    0   1   2   3
0   2   5   5   8
1   7  14   4   7
2   9   0  13  17
0  12   8  13   4
1  11  13  10   5
2   7   7  11   3
--------------------
   0   1   2   3   4
0  2   5   5   8   0
1  7  14   4   7  17
2  9   0  13  17   6
   0   1   2
0  2   7   9
1  5  14   0
2  5   4  13
3  8   7  17
4  0  17   6


In [56]:
# 数据处理
"""
处理重复数据duplicated
"""
df1 = pd.DataFrame({'d1':[1,1,1,4,5,6,7,8,9,10],
              'd2':[1,1,1,4,5,6,7,8,8,11]},index=list('abcdefghij'))
# 去除的是重复行，即样本数据相同则保留第一个其他全部丢弃
print(df1.duplicated())  # 确认重复行，返回时bool
print(df1.duplicated('d2'))
print(df1.drop_duplicates()) # 返回去重后的结果

a    False
b     True
c     True
d    False
e    False
f    False
g    False
h    False
i    False
j    False
dtype: bool
a    False
b     True
c     True
d    False
e    False
f    False
g    False
h    False
i     True
j    False
dtype: bool
   d1  d2
a   1   1
d   4   4
e   5   5
f   6   6
g   7   7
h   8   8
i   9   8
j  10  11


In [113]:
s1 = pd.Series(np.random.randint(0,10,4))
print(s1)
print(s1.map(lambda s: s + 2))
print(s1.replace([0, 3], [10, -100]))

0    1
1    0
2    6
3    7
dtype: int32
0    3
1    2
2    8
3    9
dtype: int64
0     1
1    10
2     6
3     7
dtype: int32
