In [30]:
import pandas as pd

# pandas 数据结构 Series
ser_obj = pd.Series(range(10, 20),index=list('abcdefhjkl'))
# 头部
print(ser_obj.head(9))
print(type(ser_obj.index))
print(ser_obj.index)
print(type(ser_obj.values))
print(ser_obj.values)
print(ser_obj[8])

# dict 构建series
year_dict = {2001: 123, 1382: 23.2, 2077: 21.1}
ser_obj1 = pd.Series(year_dict)
print(ser_obj1)

# 为index、series取别名
ser_obj1.name = '年份表'
ser_obj1.index.name = 'year'
print(ser_obj1)

a    10
b    11
c    12
d    13
e    14
f    15
h    16
j    17
k    18
dtype: int64
<class 'pandas.core.indexes.base.Index'>
Index(['a', 'b', 'c', 'd', 'e', 'f', 'h', 'j', 'k', 'l'], dtype='object')
<class 'numpy.ndarray'>
[10 11 12 13 14 15 16 17 18 19]
18
2001    123.0
1382     23.2
2077     21.1
dtype: float64
year
2001    123.0
1382     23.2
2077     21.1
Name: 年份表, dtype: float64


In [49]:
import numpy as np
import pandas as pd

# DataFrame的构建
a = pd.DataFrame(np.arange(12).reshape(3,4))
print(a)
b = np.random.randn(3,4)
print(b)
print('-'*20)
# dict 构建
dict_data = {'A':1,
             'B':pd.date_range('20190926',periods=4),
             'C':pd.Series(1,index=list(range(4)),dtype='float32'),
             'D':np.array([3]*4,dtype='int32'),
             'E':['python','java','c++','c'],
             'F':'wangdao'}
c = pd.DataFrame(dict_data)
print(c)
# 列索引操作
print(c['A'])
c['h']=c['C']*4
del(c['D'])
print(c)
# 索引名切片
print(c.loc['0':'2',['B','F']])
print('-'*20)
# 基于索引编号进行切片
print(c.iloc[0:3,[1,4]])
c.dtypes

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
[[ 0.15966276 -1.51436794  0.74079167  0.03841277]
 [-1.63728101  1.37417529  0.79962169  2.28971619]
 [-0.57224341  0.58040952  0.63424842 -0.69408966]]
--------------------
   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  python  wangdao
1  1 2019-09-27  1.0  3    java  wangdao
2  1 2019-09-28  1.0  3     c++  wangdao
3  1 2019-09-29  1.0  3       c  wangdao
0    1
1    1
2    1
3    1
Name: A, dtype: int64
   A          B    C       E        F    h
0  1 2019-09-26  1.0  python  wangdao  4.0
1  1 2019-09-27  1.0    java  wangdao  4.0
2  1 2019-09-28  1.0     c++  wangdao  4.0
3  1 2019-09-29  1.0       c  wangdao  4.0
           B        F
0 2019-09-26  wangdao
1 2019-09-27  wangdao
2 2019-09-28  wangdao
--------------------
           B        F
0 2019-09-26  wangdao
1 2019-09-27  wangdao
2 2019-09-28  wangdao


A             int64
B    datetime64[ns]
C           float32
E            object
F            object
h           float32
dtype: object

In [ ]:
import numpy as np
import pandas as pd
# 对齐操作