In [36]:
import numpy as np

b=np.arange(64).reshape((4, 4, 2,2))
print(b)
print('*'*20)
# 轴0元素相加，所有轴1进行叠加
print(np.sum(b, axis=0))
print('*'*20)
print(b*2)
a = np.sum(b,axis=3)
print(a.shape)
# 单行/单列的同纬度数据可以进行相加
print('分隔符')
c = np.arange(24).reshape(2,3,4)
d = np.arange(8).reshape(2,1,4)
print(c)
print(d)
print(c+d)

e = np.arange(18).reshape(3,2,3)
print(e)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]

  [[24 25]
   [26 27]]

  [[28 29]
   [30 31]]]


 [[[32 33]
   [34 35]]

  [[36 37]
   [38 39]]

  [[40 41]
   [42 43]]

  [[44 45]
   [46 47]]]


 [[[48 49]
   [50 51]]

  [[52 53]
   [54 55]]

  [[56 57]
   [58 59]]

  [[60 61]
   [62 63]]]]
********************
[[[ 96 100]
  [104 108]]

 [[112 116]
  [120 124]]

 [[128 132]
  [136 140]]

 [[144 148]
  [152 156]]]
********************
[[[[  0   2]
   [  4   6]]

  [[  8  10]
   [ 12  14]]

  [[ 16  18]
   [ 20  22]]

  [[ 24  26]
   [ 28  30]]]


 [[[ 32  34]
   [ 36  38]]

  [[ 40  42]
   [ 44  46]]

  [[ 48  50]
   [ 52  54]]

  [[ 56  58]
   [ 60  62]]]


 [[[ 64  66]
   [ 68  70]]

  [[ 72  74]
   [ 76  78]]

  [[ 80  82]
   [ 84  86]]

  [[ 88  90]
   [ 92  94]]]


 [[[ 96  98]
   [100 102]]

  [[104 106]
   [108 110]]

  [[112 114]
   [116 118]]

  [[120 122]
   [124 126]]]]
(4, 4, 2

In [37]:
import numpy as np
import random
# nparray 的生成
print(np.array([1, 2, 4]))
print(np.array(range(10)))
print(np.arange(0,4,1))

# 基本属性
a = np.arange(24).reshape(2,3,4)
print(a.ndim)
print(a.shape)
print(a.size)
# 变化形状
print(a.reshape((4,6)))

arr = np.array([random.random() for i in range(10)])
print(np.round(arr,2))

[1 2 4]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
3
(2, 3, 4)
24
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0.14 0.09 0.07 0.88 0.84 0.89 0.27 0.54 0.24 0.98]


In [128]:
a = np.arange(24).reshape(4,3,2)
print(a)
print('-'*20)
# : 取多行 ,: 取单行[可以省略]
# 1:3,: 左闭右开
# :, 取单列    :,1: 取连续多列
# nparray的取值规则，行按0轴取，列按1轴取
# a[a<20]=0
# 限制nparray的数值范围
# a= a.clip(10,20)
# 去重
print(np.unique(a, return_index = True))
# 删除
print(np.delete(a, 2,axis=1))
# 新增 1轴的第2列新增元素11
print(np.insert(a, 2, [11,12], axis=1))
# 添加数据，存在问题
#
#
#
                # print(np.append(a[:,1:], [[[1]]],axis=1))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
--------------------
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64))
[[[ 0  1]
  [ 2  3]]

 [[ 6  7]
  [ 8  9]]

 [[12 13]
  [14 15]]

 [[18 19]
  [20 21]]]
[[[ 0  1]
  [ 2  3]
  [11 12]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [11 12]
  [10 11]]

 [[12 13]
  [14 15]
  [11 12]
  [16 17]]

 [[18 19]
  [20 21]
  [11 12]
  [22 23]]]


In [141]:
a = np.array([[51,60],[12,9],[63,42]])
print(a)
# 最大值
print(np.max(a,axis=0))
# 平均值
print(np.mean(a, axis=1))

print(np.maximum([-2, -1, 0, 1, 2], 0))
# 数据趋势变化api
# std   标准差
# ptp 极值
# var 方差
# cov 协方差
# average 平均值
# median 中位数

[[51 60]
 [12  9]
 [63 42]]
[63 60]
[55.5 10.5 52.5]


''

In [153]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# concatenate默认轴0拼接，也可以指定轴
print(np.concatenate((a, b)))
# stack 二维变三维
print(np.stack((a, b), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [168]:
# 分割
a = np.arange(27).reshape(3,3,3)
print(a)
print(np.split(a, 3,axis=1))
# 水平分割、垂直
print(np.vsplit(a, 1))
print(np.hsplit(a, 1))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[array([[[ 0,  1,  2]],

       [[ 9, 10, 11]],

       [[18, 19, 20]]]), array([[[ 3,  4,  5]],

       [[12, 13, 14]],

       [[21, 22, 23]]]), array([[[ 6,  7,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])]
[array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])]
[array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])]


In [179]:
a = np.arange(24).reshape(3,4,2)
print(a)
# print(np.count_nonzero(a))
# 转置
            # print(a.reshape(2,4,3))
print(a.T)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[[[ 0  8 16]
  [ 2 10 18]
  [ 4 12 20]
  [ 6 14 22]]

 [[ 1  9 17]
  [ 3 11 19]
  [ 5 13 21]
  [ 7 15 23]]]
